### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by aquib1011** [VinAIResearch/Warping-based_Backdoor_Attack-release#11]
Is there a way in which I can access/download trojan or triggered image generated by the algorithm? If Yes how? or if there is a link I can download from.

**Comment by anhttran** [comment]
Dear,

It is not hard to generate backdoor images from the clean inputs, given the noise_grid and the system hyper-parameters:
[https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/train.py#L72,L79](https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/train.py#L72,L79)

During training, we log sample clean inputs, backdoor inputs, and residual images. You can use tensorboard to visualize the:
[https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/train.py#L146-L158](https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/train.py#L146-L158)
