### ISSUE TITLE
Questions regarding reproducing results using Neural Cleanse

### ISSUE THREAD

**Issue by openbbox** [VinAIResearch/Warping-based_Backdoor_Attack-release#3]
Hi,

Thanks for sharing the code.

I am trying to reproduce the results in the paper WaNet - Imperceptible Warping-based Backdoor Attack that evade the Neural Cleanse defense. I am using the GTSRB dataset. I download the model and dataset according to the instructions in README. When I run Neural Cleanse on the downloaded model, I get an anomaly index larger than 2 (even greater than 4), which means the trained model is still considered to be backdoored. I tested it for 10 times and got the same result.

Is there anything not configured properly? Would you be able to take a look? I'd really appreciate it.

**Comment by tuananh12101997** [comment]
Sorry for the inconvenience. We have taken a look and found out that We had packaged the wrong pretrained checkpoint of gtsrb dataset when preparing the release version. We have updated the pretrained checkpoints' link in README.md, you can check it out. Feel free to drop an email or create a thread here if you have any further questions.
