### ISSUE TITLE
Some question about  fine-pruning-celeba.py

### ISSUE THREAD

**Issue by HazardFY** [VinAIResearch/Warping-based_Backdoor_Attack-release#4]
First, thanks for your sharing. But I find that the model Resnet18 doesn't have the parameter ind.  What's more,  layer4.bn2 layer does not modify the number of input channels while layer4[1].conv2 has been changed. Is that OK? Or I dismiss  something?  Looking forward to your reply

**Comment by tuananh12101997** [comment]
Thanks for your questions. As far as I understand, you are talking about: (1) **ind** assignment in [https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/defenses/fine_pruning/fine-pruning-celeba.py#L155](url), and (2) If **layer4.bn2** has modified number of input channels. 

1. the **ind** parameter is not of Resnet18 model, it is of ResNet's Blocks. You can check out the definition of those modules in [https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/classifier_models/resnet.py#L14](url) and [https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/classifier_models/resnet.py#L43](url). 

2. The modifying steps start from [https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/defenses/fine_pruning/fine-pruning-celeba.py#L150](url). It is basically modifying **bn2**'s params data as well as its params datas' dimensions.

**Comment by HazardFY** [comment]
Thanks for your answer. For the first question before, I find that I didn't download the latest version of the code. But I still have some questions about [https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/tree/main/defenses/fine_pruning/fine-pruning-celeba.py](url).
