### ISSUE TITLE
About finetune defense

### ISSUE THREAD

**Issue by bingxumu** [VinAIResearch/Warping-based_Backdoor_Attack-release#5]
Hi! Thanks for your sharing! This attack is cool!

Have you tested whether the attack is still effective after using 5% of clean data to fintune the backdoor model?
I finetune the backdoor model on the 5%  clean training data for 10 epochs using the SGD optimizer.  According to the results, it can be seen that this strategy is defensive against wanet. Have you tested it?  The pretrained model that you provided is used.

**Comment by tuananh12101997** [comment]
Thanks for your interest in our paper.

You are right indeed. Catastrophic forgetting is the major limitation of our paper, and many other works in backdoor attacks as well. Actually, that is the problem we are working on right now.
