### ISSUE TITLE
about the grid_temps

### ISSUE THREAD

**Issue by skysunsun** [VinAIResearch/Warping-based_Backdoor_Attack-release#7]
Thanks for your great work.I have a question about grid_temps.After grid_temps is initialized, it has not changed, because it has not been optimized, so the perturbation is the same for every data?

**Comment by tuananh12101997** [comment]
Thank you for your interest in our work.

The grid_temps, as you recognized, has not changed once initialized. But the perturbation is not the same for every data, as the grid_temps encodes the **relative position** between the pixels in original images and warped images. Therefore, the perturbation would change w.r.t the content of the original images.
