### ISSUE TITLE
all2all-attack

### ISSUE THREAD

**Issue by xcatf** [VinAIResearch/Warping-based_Backdoor_Attack-release#9]
According to the definition of all-to-all in the paper **“WaNet - Imperceptible Warping-based Backdoor Attack”**
![image](https://user-images.githubusercontent.com/40793234/170200970-e9077db0-c4d9-4a94-bc6a-8b3696e6d07b.png)
**which is all-to-all: c(y) = (y + 1) % |C|** 
However, in your code [train.py](https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/main/train.py) , the all-to-all attack modifies the labels as: **c(y) = y % |C|**
The specific code is (**Lines 82 to 83 in** **train.py**):
![image](https://user-images.githubusercontent.com/40793234/170200484-63704884-7d83-424f-9599-857f305a843f.png)
Is there something wrong here? 
should it be modified to: 
`            targets_bd = torch.remainder(targets[:num_bd] + 1, opt.num_classes)
`

**Comment by tuananh12101997** [comment]
Thank you for pointing out the glitch. That was a mistake when I cleaned the codebase for the released version. 
I will update asap.
